---
name: Deployment (Create)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  deploymentJobId: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }} # Unique ID for the deployment job

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/bicep-deploy@v1
        with:
          operation: create
          type: deployment
          name: main-${{env.deploymentJobId}}
          location: australiaeast
          scope: managementGroup
          management-group-id: mg-alz
          template-file: ./src/orchestration/main.bicep
          parameters-file: ./src/configuration/lz.bicepparam